<template>
  <div class="about-container">
 
      <h3 class="description-title">
          ABOUT
      </h3>

      <p class="description-text">
          The future of live events lies in the ability for the auidence to play a role in shaping the events experience.
          
          <br />
          <br />
          
          Our phones have given us the ability to document, share, and respond to a myriad of real-time events
          through a variety of platforms.
          <br />
          <br />
          We asked ourselves if there was a way that the vast expanse of data emitted at these events could create a feedback loop
          in which technology provided was a medium by which the auidence could augment their experience rather than just document it.
          <br />
          <br />
          And so Mixed Signals was created. Our first product -- and flagship product -- is a visualizer for display during live events and a
          companion app that allows audience members to project text, images, and other media. The visualizer renders this data which in turn creates a curated
          atmosphere generated by the auidence as a whole.
      </p>
  </div>
</template>

<script>
export default {
    components: {},
    props: [],
    data() {
        return {

        }
    }
}
</script>

<style>
    
    .about-container {
        width: 100%;
        height: 100%;
        padding: 10px;

    }
</style>    